name: CI

on: push

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: pruebas-unitarias
        run: mvn test
      - name: empaquetar
        run: mvn package -DskipTests=true

  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: pruebas-funcionales
        run: echo "pruebas-funcionales"
  
  qa:
    needs: test
    runs-on: self-hosted
    steps:
      - name: calidad-codigo
        run: echo "calidad-codigo"

  deploy:
    needs: qa
    runs-on: ubuntu-latest
    steps:
      - name: despliegue
        run: echo "despliegue"
